# Generated by Django 5.2.17 on 2026-08-25 05:33

import django.db.models.deletion
from django.db import migrations, models


def link_existing_guardians(apps, schema_editor):
    Guardian = apps.get_model('students', 'Guardian')
    Student = apps.get_model('students', 'Student')
    guardians = {}
    for student in Student.objects.all().iterator():
        name = student.guardian_name.strip()
        phone = student.guardian_phone.strip()
        key = (name.casefold(), phone.casefold())
        guardian = guardians.get(key)
        if guardian is None:
            guardian = Guardian.objects.create(name=name, phone=phone)
            guardians[key] = guardian
        student.primary_guardian_id = guardian.id
        student.save(update_fields=['primary_guardian'])


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='students_gu_name_1ed15d_idx'), models.Index(fields=['phone'], name='students_gu_phone_a1a96b_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'phone'), name='unique_guardian_name_phone')],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='primary_guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.guardian'),
        ),
        migrations.RunPython(link_existing_guardians, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['primary_guardian', 'status'], name='students_st_primary_cb0623_idx'),
        ),
    ]
