# Generated by Django 5.2.17 on 2026-08-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_profile_image_pathname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_relationship',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
