import {useEffect,useState} from 'react';
import {Edit,MessageSquarePlus,Trash2} from 'lucide-react';
import {api} from '../services/api';
import {apiErrorMessage} from '../utils/apiError';
import type {Page,StudentNote} from '../types';
import {Button,Empty,Skeleton,Textarea} from './UI';
import ConfirmDialog from './ConfirmDialog';
import Feedback from './Feedback';
import Pagination from './Pagination';
import {useAuth} from '../context/auth';

export default function StudentNotes({studentId}:{studentId:number}){
  const {user}=useAuth(); const [page,setPage]=useState<Page<StudentNote>|null>(null); const [pageNumber,setPageNumber]=useState(1); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [feedback,setFeedback]=useState(''); const [content,setContent]=useState(''); const [editing,setEditing]=useState<StudentNote|null>(null); const [remove,setRemove]=useState<StudentNote|null>(null); const [busy,setBusy]=useState(false);
  async function load(){try{setPage((await api.get<Page<StudentNote>>(`/students/notes/?student=${studentId}&page=${pageNumber}`)).data);setError('');}catch(reason){setPage(null);setError(apiErrorMessage(reason,'Unable to load student notes.'));}finally{setLoading(false);}}
  useEffect(()=>{let active=true;api.get<Page<StudentNote>>(`/students/notes/?student=${studentId}&page=${pageNumber}`).then(({data})=>{if(active){setPage(data);setError('');}}).catch(reason=>{if(active){setPage(null);setError(apiErrorMessage(reason,'Unable to load student notes.'));}}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[studentId,pageNumber]);
  async function save(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{if(editing)await api.patch(`/students/notes/${editing.id}/`,{content});else await api.post('/students/notes/',{student:studentId,content});setContent('');setEditing(null);setFeedback(editing?'Note updated.':'Note added.');await load();}catch(reason){setError(apiErrorMessage(reason,'Unable to save this note.'));}finally{setBusy(false);}}
  async function confirmDelete(){if(!remove)return;setBusy(true);try{await api.delete(`/students/notes/${remove.id}/`);setRemove(null);setFeedback('Note deleted.');if(page?.results.length===1&&pageNumber>1)setPageNumber(value=>value-1);else await load();}catch(reason){setRemove(null);setError(apiErrorMessage(reason,'Unable to delete this note.'));}finally{setBusy(false);}}
  return <div className="notes-panel">{feedback&&<Feedback message={feedback} onDismiss={()=>setFeedback('')}/>} {error&&<Feedback tone="error" message={error} onDismiss={()=>setError('')}/>}<form onSubmit={save}><Textarea label={editing?'Edit authored note':'Add a teacher note'} rows={3} required value={content} onChange={event=>setContent(event.target.value)} placeholder="Record an observation or follow-up…"/><div className="actions">{editing&&<Button type="button" className="secondary" onClick={()=>{setEditing(null);setContent('');}}>Cancel</Button>}<Button disabled={busy||!content.trim()}>{editing?'Save note':<><MessageSquarePlus size={16}/> Add note</>}</Button></div></form>{loading?<Skeleton rows={3}/>:page?.results.length?<div className="note-list">{page.results.map(note=>{const canManage=Boolean(user?.is_admin||note.author===user?.id);return <article key={note.id}><p>{note.content}</p><footer><span><strong>{note.author_name||'Unknown author'}</strong> · {new Date(note.created_at).toLocaleString()}{note.updated_at!==note.created_at&&' · edited'}</span>{canManage&&<span className="row-actions"><Button className="ghost compact" onClick={()=>{setEditing(note);setContent(note.content);}}><Edit size={14}/> Edit</Button><Button className="ghost compact" onClick={()=>setRemove(note)}><Trash2 size={14}/> Delete</Button></span>}</footer></article>;})}<Pagination page={pageNumber} total={page.count} pageSize={20} hasPrevious={Boolean(page.previous)} hasNext={Boolean(page.next)} onPage={setPageNumber}/></div>:!error&&<Empty text="No teacher notes" description="Authored notes for this student will appear here."/>}<ConfirmDialog open={Boolean(remove)} title="Delete this note?" message="This authored note will be permanently removed." confirmLabel="Delete note" danger busy={busy} onCancel={()=>setRemove(null)} onConfirm={confirmDelete}/></div>;
}
