import {useCallback,useEffect,useState} from 'react';
import {Search,ShieldAlert} from 'lucide-react';
import {useSearchParams} from 'react-router-dom';
import {api} from '../../services/api';
import {apiErrorMessage} from '../../utils/apiError';
import {Avatar,Badge,Button,Card,Empty,PageHeader,Skeleton} from '../../components/UI';
import Feedback from '../../components/Feedback';
import Pagination from '../../components/Pagination';
import type {AuditLog,Page} from '../../types';

const actionLabel=(value:string)=>value.replace(/^(user|teacher_profile)_/,'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const category=(value:string)=>value.includes('delete')||value.includes('deactiv')?'delete':value.includes('creat')||value.includes('activat')?'create':value.includes('superuser')||value.includes('staff')||value.includes('password')||value.includes('role')?'security':'update';

export default function AuditLogs(){
  const [params,setParams]=useSearchParams();const query=params.toString();const page=Number(params.get('page')||1);
  const [data,setData]=useState<Page<AuditLog>|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [selected,setSelected]=useState<AuditLog|null>(null);
  const [filters,setFilters]=useState({action:params.get('action')||'',object_type:params.get('object_type')||'',user:params.get('user')||''});
  const load=useCallback(async()=>{try{const {data:result}=await api.get<Page<AuditLog>>(`/audit/?${query}`);setData(result);setError('');}catch(reason){setData(null);setError(apiErrorMessage(reason,'Unable to load audit logs.'));}finally{setLoading(false);}},[query]);
  useEffect(()=>{let active=true;api.get<Page<AuditLog>>(`/audit/?${query}`).then(({data:result})=>{if(active){setData(result);setError('');}}).catch(reason=>{if(active){setData(null);setError(apiErrorMessage(reason,'Unable to load audit logs.'));}}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[query]);
  function apply(event:React.FormEvent){event.preventDefault();setLoading(true);const next=new URLSearchParams();Object.entries(filters).forEach(([key,value])=>{if(value.trim())next.set(key,value.trim());});setParams(next);}
  function setPage(value:number){setLoading(true);const next=new URLSearchParams(params);next.set('page',String(value));setParams(next);}
  return <><PageHeader eyebrow="Security & governance" title="Audit Logs" description="Monitor privileged user-management and domain activity across the system."/><Card>
    <form className="toolbar audit-filters" onSubmit={apply}><label className="search"><Search size={17}/><input aria-label="Filter by action" placeholder="Exact action" value={filters.action} onChange={e=>setFilters(current=>({...current,action:e.target.value}))}/></label><input aria-label="Filter by object type" placeholder="Object type" value={filters.object_type} onChange={e=>setFilters(current=>({...current,object_type:e.target.value}))}/><input aria-label="Filter by actor user ID" inputMode="numeric" placeholder="Actor user ID" value={filters.user} onChange={e=>setFilters(current=>({...current,user:e.target.value}))}/><Button type="submit">Apply</Button>{query&&<Button type="button" className="secondary" onClick={()=>{setFilters({action:'',object_type:'',user:''});setParams({});}}>Clear</Button>}</form>
    {error&&<div className="error-actions"><Feedback tone="error" message={error}/><Button type="button" className="secondary" onClick={()=>{setLoading(true);void load();}}>Retry</Button></div>}
    {loading?<Skeleton rows={7}/>:data?.results.length?<><div className="table-wrap"><table><caption className="visually-hidden">Audit activity records</caption><thead><tr><th>Timestamp</th><th>Actor</th><th>Action</th><th>Object</th><th>Details</th></tr></thead><tbody>{data.results.map(log=>{const date=new Date(log.timestamp),kind=category(log.action),actor=log.user_name||'System';return <tr key={log.id}><td><strong>{date.toLocaleDateString()}</strong><small className="table-secondary">{date.toLocaleTimeString()}</small></td><td><div className="actor-cell"><Avatar name={actor} size="sm"/><span><strong>{actor}</strong><small>{log.user_name?'Authenticated actor':'System'}</small></span></div></td><td><Badge tone={kind}>{actionLabel(log.action)}</Badge></td><td>{log.object_type} #{log.object_id||'—'}</td><td><Button type="button" className="secondary compact" onClick={()=>setSelected(log)}>View details</Button></td></tr>;})}</tbody></table></div><Pagination page={page} total={data.count} hasPrevious={Boolean(data.previous)} hasNext={Boolean(data.next)} onPage={setPage}/></>:!error&&<Empty icon={ShieldAlert} text="No audit activity found" description="Try adjusting the current filters."/>}
  </Card>{selected&&<div className="dialog-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setSelected(null);}}><section className="details-dialog" role="dialog" aria-modal="true" aria-labelledby="activity-title"><div className="page-title"><div><span className="eyebrow">Audit record</span><h2 id="activity-title">Activity Details</h2></div></div><dl className="metadata-grid"><div><dt>Action</dt><dd>{actionLabel(selected.action)}</dd></div><div><dt>Actor</dt><dd>{selected.user_name||'System'}</dd></div><div><dt>Object</dt><dd>{selected.object_type} #{selected.object_id||'—'}</dd></div><div><dt>Timestamp</dt><dd>{new Date(selected.timestamp).toLocaleString()}</dd></div><div><dt>Metadata</dt><dd><pre>{JSON.stringify(selected.metadata||{},null,2)}</pre></dd></div></dl><div className="actions"><Button type="button" className="secondary" onClick={()=>setSelected(null)}>Close</Button></div></section></div>}</>;
}
