import {useEffect, useState} from 'react';
import {Link, useLocation, useParams} from 'react-router-dom';
import {KeyRound, Pencil, ShieldCheck, UserCheck, UserCog, UserMinus} from 'lucide-react';
import {api} from '../../services/api';
import {apiErrorMessage} from '../../utils/apiError';
import {useAuth} from '../../context/auth';
import {Avatar, Badge, Button, Card, Input, PageHeader, Select, Skeleton} from '../../components/UI';
import ConfirmDialog from '../../components/ConfirmDialog';
import Feedback from '../../components/Feedback';
import type {ManagedUser} from '../../types';

type Confirmation = {title: string; message: string; label: string; danger: boolean; run: () => Promise<void>};

export default function UserDetails() {
  const {id} = useParams();
  const {user: current} = useAuth();
  const location = useLocation();
  const [account, setAccount] = useState<ManagedUser | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [feedback, setFeedback] = useState((location.state as {message?: string} | null)?.message || '');
  const [busy, setBusy] = useState(false);
  const [confirmation, setConfirmation] = useState<Confirmation | null>(null);
  const [role, setRole] = useState<'admin' | 'teacher'>('teacher');
  const [passwordOpen, setPasswordOpen] = useState(false);
  const [password, setPassword] = useState('');
  const [passwordConfirm, setPasswordConfirm] = useState('');
  async function load() {if (!id) return; const response = await api.get<ManagedUser>(`/users/${id}/`); setAccount(response.data); setRole(response.data.role);}
  useEffect(() => {let active = true; if (!id) return; api.get<ManagedUser>(`/users/${id}/`).then(response => {if (active) {setAccount(response.data); setRole(response.data.role);}}).catch(reason => {if (active) setError(apiErrorMessage(reason, 'Unable to load user details.'));}).finally(() => {if (active) setLoading(false);}); return () => {active = false;};}, [id]);
  function action(title: string, message: string, label: string, endpoint: string, payload: unknown, success: string, danger = false) {setConfirmation({title, message, label, danger, run: async () => {setBusy(true); setError(''); try {await api.post(endpoint, payload); await load(); setFeedback(success); setConfirmation(null);} catch (reason) {setError(apiErrorMessage(reason, 'Unable to update this account.')); setConfirmation(null);} finally {setBusy(false);}}});}
  async function setNewPassword(event: React.FormEvent) {event.preventDefault(); if (busy || !id) return; setBusy(true); setError(''); try {await api.post(`/users/${id}/set-password/`, {password, password_confirm: passwordConfirm}); setPassword(''); setPasswordConfirm(''); setPasswordOpen(false); setFeedback('Password updated successfully.');} catch (reason) {setError(apiErrorMessage(reason, 'Unable to update the password.'));} finally {setBusy(false);}}
  if (loading) return <Skeleton rows={6}/>;
  if (!account) return <Feedback tone="error" message={error || 'Unable to load user details.'}/>;
  const ownAccount = account.id === current?.id;
  const displayName = `${account.first_name} ${account.last_name}`.trim() || account.username;
  return <>
    <PageHeader eyebrow="Account management" title="User Details" description="Review identity, application access, and protected system privileges." actions={<Link className="btn" to={`/superuser/users/${account.id}/edit`}><Pencil size={17}/> Edit profile</Link>}/>
    <div className="profile-hero"><Avatar name={displayName} size="lg"/><div><h1>{displayName} {ownAccount && <Badge tone="superuser">Your account</Badge>}</h1><p>@{account.username} · {account.email || 'No email address'}</p></div><span className="profile-status"><Badge tone={account.is_active ? 'active' : 'inactive'}>{account.is_active ? 'Active account' : 'Inactive account'}</Badge></span></div>
    {feedback && <Feedback message={feedback} onDismiss={() => setFeedback('')}/>} {error && <Feedback tone="error" message={error} onDismiss={() => setError('')}/>}<div className="profile-grid">
      <Card><h2>Account Information</h2><dl><dt>Full name</dt><dd>{displayName}</dd><dt>Username</dt><dd>@{account.username}</dd><dt>Email</dt><dd>{account.email || '—'}</dd><dt>Date joined</dt><dd>{new Date(account.date_joined).toLocaleString()}</dd><dt>Last login</dt><dd>{account.last_login ? new Date(account.last_login).toLocaleString() : 'Never'}</dd></dl></Card>
      <Card><h2>Access & Permissions</h2><dl><dt>Application Role</dt><dd><Badge tone={account.role}>{account.role}</Badge></dd><dt>Account Status</dt><dd><Badge tone={account.is_active ? 'active' : 'inactive'}>{account.is_active ? 'Active' : 'Inactive'}</Badge></dd><dt>Django Staff</dt><dd>{account.is_staff ? <Badge tone="staff">Enabled</Badge> : 'Disabled'}</dd><dt>System Superuser</dt><dd>{account.is_superuser ? <Badge tone="superuser">Granted</Badge> : 'Not granted'}</dd></dl></Card>
      {account.teacher_profile && <Card><h2>Teacher Profile</h2><dl><dt>Profile ID</dt><dd>{account.teacher_profile.id}</dd><dt>Phone</dt><dd>{account.teacher_profile.phone || '—'}</dd><dt>Status</dt><dd><Badge tone={account.teacher_profile.is_active ? 'active' : 'inactive'}>{account.teacher_profile.is_active ? 'Active' : 'Inactive'}</Badge></dd><dt>Assigned students</dt><dd>{account.teacher_profile.student_count}</dd></dl></Card>}
      <Card className="wide"><h2>Account Actions</h2><div className="privilege-explainer"><div><strong>Application Role</strong><span>Controls administrator or teacher behavior inside the application.</span></div><div><strong>Django Staff Access</strong><span>Controls Django `/admin/` access independently.</span></div><div><strong>System Superuser</strong><span>Grants the highest system-level privilege.</span></div></div><div className="management-actions">
        <div><Select label="Application role" value={role} onChange={event => setRole(event.target.value as 'admin' | 'teacher')}><option value="admin">Application Admin</option><option value="teacher">Teacher</option></Select><Button type="button" disabled={busy || role === account.role} onClick={() => action('Change application role?', `Change ${account.username} from ${account.role} to ${role}? Teacher profiles are preserved by the backend.`, 'Change role', `/users/${account.id}/role/`, {role}, 'Application role updated.')}><UserCog size={17}/> Change role</Button></div>
        <div><span><strong>Account activation</strong><small>{account.is_active ? 'Deactivate to prevent authentication.' : 'Activate to restore authentication.'}</small></span><Button type="button" className={account.is_active ? 'danger' : ''} disabled={busy || (ownAccount && account.is_active)} onClick={() => action(account.is_active ? 'Deactivate this user?' : 'Activate this user?', account.is_active ? `${account.username} will no longer be able to sign in.` : `${account.username} will be able to authenticate again.`, account.is_active ? 'Deactivate' : 'Activate', `/users/${account.id}/${account.is_active ? 'deactivate' : 'activate'}/`, {}, account.is_active ? 'User deactivated.' : 'User activated.', account.is_active)}>{account.is_active ? <UserMinus size={17}/> : <UserCheck size={17}/>} {account.is_active ? 'Deactivate' : 'Activate'}</Button></div>
        <div><span><strong>Django Admin Staff Access</strong><small>{account.is_staff ? 'User can access Django Admin.' : 'User cannot access Django Admin.'}</small></span><Button type="button" className="secondary" disabled={busy} onClick={() => action('Change Django staff access?', `${account.is_staff ? 'Remove' : 'Grant'} Django /admin/ access for ${account.username}?`, account.is_staff ? 'Remove staff access' : 'Grant staff access', `/users/${account.id}/staff/`, {is_staff: !account.is_staff}, account.is_staff ? 'Django staff access removed.' : 'Django staff access granted.', account.is_staff)}><UserCog size={17}/> {account.is_staff ? 'Remove staff' : 'Grant staff'}</Button></div>
        <div><span><strong>System Superuser</strong><small>{account.is_superuser ? 'Full system privileges are granted.' : 'Standard system privilege level.'}</small></span><Button type="button" className={!account.is_superuser ? 'danger' : 'secondary'} disabled={busy || (ownAccount && account.is_superuser)} onClick={() => action(account.is_superuser ? 'Remove superuser privileges?' : 'Grant superuser privileges?', account.is_superuser ? `Remove full system privileges from ${account.username}?` : `This grants ${account.username} full system-level administrative privileges.`, account.is_superuser ? 'Remove superuser' : 'Grant superuser', `/users/${account.id}/superuser/`, {is_superuser: !account.is_superuser}, account.is_superuser ? 'Superuser privileges removed.' : 'Superuser privileges granted.', true)}><ShieldCheck size={17}/> {account.is_superuser ? 'Remove superuser' : 'Grant superuser'}</Button></div>
        <div><span><strong>Administrative password</strong><small>Set a new password without retrieving the existing password.</small></span><Button type="button" className="secondary" disabled={busy} onClick={() => setPasswordOpen(value => !value)}><KeyRound size={17}/> Set password</Button></div>
      </div>{ownAccount && <p className="form-note">Self-deactivation and self-removal of superuser status remain disabled here and protected by the backend.</p>}{passwordOpen && <form className="password-panel" onSubmit={setNewPassword}><h3>Set a new password</h3><div className="form-grid"><Input label="New password" type="password" required autoComplete="new-password" value={password} onChange={event => setPassword(event.target.value)}/><Input label="Confirm password" type="password" required autoComplete="new-password" value={passwordConfirm} onChange={event => setPasswordConfirm(event.target.value)}/></div><div className="actions"><Button type="button" className="secondary" disabled={busy} onClick={() => {setPasswordOpen(false); setPassword(''); setPasswordConfirm('');}}>Cancel</Button><Button disabled={busy}>{busy ? 'Updating…' : 'Update password'}</Button></div></form>}</Card>
    </div><ConfirmDialog open={Boolean(confirmation)} title={confirmation?.title || ''} message={confirmation?.message || ''} confirmLabel={confirmation?.label} danger={confirmation?.danger} busy={busy} onCancel={() => {if (!busy) setConfirmation(null);}} onConfirm={async () => {await confirmation?.run();}}/>
  </>;
}
