# Generated by Django 5.2.17 on 2026-08-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile_image_pathname',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
