# Generated by Django 5.2.17 on 2026-08-25 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_sessions_for_existing_attendance(apps, schema_editor):
    Attendance = apps.get_model('attendance', 'Attendance')
    AttendanceSession = apps.get_model('attendance', 'AttendanceSession')
    Teacher = apps.get_model('teachers', 'Teacher')
    sessions = {}
    for record in Attendance.objects.all().iterator():
        key = (record.date, record.recorded_by_id)
        session = sessions.get(key)
        if session is None:
            teacher = Teacher.objects.filter(user_id=record.recorded_by_id).first()
            session = AttendanceSession.objects.create(date=record.date, title='Migrated attendance', teacher=teacher, created_by_id=record.recorded_by_id)
            sessions[key] = session
        record.session_id = session.id
        record.save(update_fields=['session'])


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions_created', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sessions', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='attendance.attendancesession'),
        ),
        migrations.RunPython(create_sessions_for_existing_attendance, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['teacher', 'date'], name='attendance__teacher_590c17_idx'),
        ),
    ]
