import {useEffect,useMemo,useState} from 'react';
import {CalendarCheck,CheckCircle2,Clock3,Edit,Trash2,UserX,X} from 'lucide-react';
import {useSearchParams} from 'react-router-dom';
import {api} from '../services/api';
import {apiErrorMessage} from '../utils/apiError';
import {getAllPages} from '../utils/pagination';
import {useAuth} from '../context/auth';
import {Badge,Button,Card,Empty,Input,PageHeader,Select,Skeleton,StatCard,Textarea} from '../components/UI';
import Pagination from '../components/Pagination';
import ConfirmDialog from '../components/ConfirmDialog';
import Feedback from '../components/Feedback';
import type {AttendanceRecord,AttendanceSession,AttendanceStatus,Page,Student,Teacher} from '../types';

const statuses:AttendanceStatus[]=['present','absent','late','excused'];
type SessionForm={date:string;title:string;teacher:string;notes:string};
const newSession=():SessionForm=>({date:new Date().toISOString().slice(0,10),title:'',teacher:'',notes:''});
async function fetchAttendance(query:string){const source=new URLSearchParams(query);const allowed=['student','status','session','date','date_after','date_before','ordering','page'];const recordParams=new URLSearchParams();allowed.forEach(k=>{const value=source.get(k);if(value)recordParams.set(k,value);});const sessionPage=source.get('session_page')||'1';const filtered=recordParams.toString();const [recordPage,sessionPageData,statistics]=await Promise.all([api.get<Page<AttendanceRecord>>(`/attendance/?${filtered}`),api.get<Page<AttendanceSession>>(`/attendance/sessions/?page=${sessionPage}`),api.get<Record<string,number>>(`/attendance/statistics/?${filtered}`)]);return {recordPage:recordPage.data,sessionPage:sessionPageData.data,statistics:statistics.data};}

export default function Attendance(){
  const {user}=useAuth();const [params,setParams]=useSearchParams();const query=params.toString();
  const [students,setStudents]=useState<Student[]>([]);const [teachers,setTeachers]=useState<Teacher[]>([]);const [sessionOptions,setSessionOptions]=useState<AttendanceSession[]>([]);const [sessions,setSessions]=useState<Page<AttendanceSession>|null>(null);const [records,setRecords]=useState<Page<AttendanceRecord>|null>(null);const [stats,setStats]=useState<Record<string,number>>({});const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [feedback,setFeedback]=useState('');
  const [sessionForm,setSessionForm]=useState<SessionForm>(newSession());const [editingSession,setEditingSession]=useState<AttendanceSession|null>(null);const [rosterSession,setRosterSession]=useState<AttendanceSession|null>(null);const [marks,setMarks]=useState<Record<number,AttendanceStatus>>({});const [recordForm,setRecordForm]=useState<AttendanceRecord|null>(null);const [busy,setBusy]=useState(false);const [remove,setRemove]=useState<{kind:'record'|'session';id:number}|null>(null);
  const selectedStudent=useMemo(()=>students.find(s=>String(s.id)===params.get('student')),[students,params]);
  async function load(refreshSessionOptions=false){try{const [data,options]=await Promise.all([fetchAttendance(query),refreshSessionOptions?getAllPages<AttendanceSession>('/attendance/sessions/'):Promise.resolve(null)]);setRecords(data.recordPage);setSessions(data.sessionPage);setStats(data.statistics);if(options)setSessionOptions(options);setError('');}catch(reason){setError(apiErrorMessage(reason,'Unable to load attendance.'));setRecords(null);setSessions(null);setStats({});}finally{setLoading(false);}}
  useEffect(()=>{let active=true;fetchAttendance(query).then(data=>{if(active){setRecords(data.recordPage);setSessions(data.sessionPage);setStats(data.statistics);setError('');}}).catch(reason=>{if(active){setError(apiErrorMessage(reason,'Unable to load attendance.'));setRecords(null);setSessions(null);setStats({});}}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[query]);
  useEffect(()=>{let active=true;Promise.all([getAllPages<Student>('/students/?status=active'),user?.is_admin?getAllPages<Teacher>('/teachers/?is_active=true'):Promise.resolve([]),getAllPages<AttendanceSession>('/attendance/sessions/')]).then(([studentRows,teacherRows,sessionRows])=>{if(active){setStudents(studentRows);setTeachers(teacherRows);setSessionOptions(sessionRows);}}).catch(reason=>{if(active)setError(apiErrorMessage(reason,'Unable to load attendance options.'));});return()=>{active=false;};},[user?.is_admin]);
  function setFilter(key:string,value:string){setLoading(true);const next=new URLSearchParams(params);if(value)next.set(key,value);else next.delete(key);if(key!=='page'&&key!=='session_page')next.delete('page');setParams(next);}
  function beginSession(row?:AttendanceSession){setEditingSession(row||null);setSessionForm(row?{date:row.date,title:row.title,teacher:String(row.teacher||''),notes:row.notes}:newSession());}
  async function saveSession(){if(busy)return;setBusy(true);setError('');const payload={date:sessionForm.date,title:sessionForm.title,notes:sessionForm.notes,...(user?.is_admin?{teacher:sessionForm.teacher?Number(sessionForm.teacher):null}:{})};try{const {data}=editingSession?await api.patch<AttendanceSession>(`/attendance/sessions/${editingSession.id}/`,payload):await api.post<AttendanceSession>('/attendance/sessions/',payload);setEditingSession(null);setSessionForm(newSession());setFeedback(editingSession?'Session updated.':'Session created.');if(!editingSession){setRosterSession(data);setMarks(Object.fromEntries(students.map(student=>[student.id,'present'])));}await load(true);}catch(reason){setError(apiErrorMessage(reason,'Unable to save attendance session.'));}finally{setBusy(false);}}
  async function saveRoster(){if(!rosterSession)return;setBusy(true);try{await api.post('/attendance/bulk/',{records:students.map(student=>({student:student.id,date:rosterSession.date,status:marks[student.id]||'present',session:rosterSession.id}))});setRosterSession(null);setFeedback('Attendance roster saved.');await load();}catch(reason){setError(apiErrorMessage(reason,'Unable to save attendance.'));}finally{setBusy(false);}}
  async function saveRecord(){if(!recordForm)return;setBusy(true);try{await api.patch(`/attendance/${recordForm.id}/`,{date:recordForm.date,status:recordForm.status,session:recordForm.session,notes:recordForm.notes});setRecordForm(null);setFeedback('Attendance record updated.');await load();}catch(reason){setError(apiErrorMessage(reason,'Unable to update attendance.'));}finally{setBusy(false);}}
  async function confirmDelete(){if(!remove)return;setBusy(true);try{const refreshOptions=remove.kind==='session';await api.delete(`/attendance/${refreshOptions?'sessions/':''}${remove.id}/`);setRemove(null);setFeedback(`${refreshOptions?'Session':'Attendance record'} deleted.`);await load(refreshOptions);}catch(reason){setError(apiErrorMessage(reason,'Unable to delete this attendance item.'));setRemove(null);}finally{setBusy(false);}}
  if(loading&&!records)return <><PageHeader eyebrow="Daily operations" title="Attendance" description="Loading attendance sessions and assigned students."/><Skeleton rows={4} cards/></>;
  return <><PageHeader eyebrow="Daily operations" title="Attendance" description={`Create sessions and manage attendance for ${user?.is_admin?'all students':'your assigned students'}.`}/>{feedback&&<Feedback message={feedback} onDismiss={()=>setFeedback('')}/>} {error&&<Feedback tone="error" message={error} onDismiss={()=>setError('')}/>} {params.get('student')&&<div className="filter-notice"><span>Showing attendance for <strong>{selectedStudent?.full_name||`student #${params.get('student')}`}</strong></span><Button className="secondary compact" onClick={()=>setFilter('student','')}><X size={15}/> Clear Student</Button></div>}
    <div className="stats"><StatCard label="Total records" value={stats.total||0} icon={CalendarCheck}/><StatCard label="Attendance rate" value={`${stats.attendance_percentage||0}%`} icon={CheckCircle2}/><StatCard label="Present / Late" value={`${stats.present||0} / ${stats.late||0}`} icon={CheckCircle2} tone="emerald"/><StatCard label="Absent / Excused" value={`${stats.absent||0} / ${stats.excused||0}`} icon={UserX} tone="red"/></div>
    <div className="grid-2"><Card><form onSubmit={event=>{event.preventDefault();void saveSession();}}><h2>{editingSession?'Edit':'New'} attendance session</h2><div className="form-grid"><Input label="Date" type="date" required value={sessionForm.date} onChange={e=>setSessionForm({...sessionForm,date:e.target.value})}/><Input label="Session title" value={sessionForm.title} onChange={e=>setSessionForm({...sessionForm,title:e.target.value})}/>{user?.is_admin&&<Select label="Teacher" value={sessionForm.teacher} onChange={e=>setSessionForm({...sessionForm,teacher:e.target.value})}><option value="">No dedicated Teacher</option>{teachers.map(t=><option key={t.id} value={t.id}>{t.first_name} {t.last_name}</option>)}</Select>}</div><Textarea label="Session notes" rows={3} value={sessionForm.notes} onChange={e=>setSessionForm({...sessionForm,notes:e.target.value})}/><div className="actions">{editingSession&&<Button type="button" className="secondary" onClick={()=>{setEditingSession(null);setSessionForm(newSession());}}>Cancel</Button>}<Button type="submit" disabled={busy||!sessionForm.date}>{editingSession?'Save session':'Create session'}</Button></div></form></Card>
      <Card><h2>Attendance filters</h2><div className="form-grid"><Select label="Student" value={params.get('student')||''} onChange={e=>setFilter('student',e.target.value)}><option value="">All students</option>{students.map(s=><option key={s.id} value={s.id}>{s.full_name}</option>)}</Select><Select label="Status" value={params.get('status')||''} onChange={e=>setFilter('status',e.target.value)}><option value="">All statuses</option>{statuses.map(s=><option key={s}>{s}</option>)}</Select><Select label="Session" value={params.get('session')||''} onChange={e=>setFilter('session',e.target.value)}><option value="">All sessions</option>{sessionOptions.map(s=><option key={s.id} value={s.id}>{s.title||s.date}</option>)}</Select><Select label="Ordering" value={params.get('ordering')||'-date'} onChange={e=>setFilter('ordering',e.target.value)}><option value="-date">Newest date</option><option value="date">Oldest date</option><option value="status">Status</option><option value="-created_at">Recently recorded</option></Select><Input label="Date from" type="date" value={params.get('date_after')||''} onChange={e=>setFilter('date_after',e.target.value)}/><Input label="Date to" type="date" value={params.get('date_before')||''} onChange={e=>setFilter('date_before',e.target.value)}/></div></Card></div>
    {rosterSession&&<Card><h2>Mark attendance — {rosterSession.title||rosterSession.date}</h2>{students.length?<div className="table-wrap"><table><thead><tr><th>Student</th><th>Status</th></tr></thead><tbody>{students.map(student=><tr key={student.id}><td><strong>{student.full_name}</strong></td><td><Select aria-label={`Attendance status for ${student.full_name}`} value={marks[student.id]||'present'} onChange={e=>setMarks(current=>({...current,[student.id]:e.target.value as AttendanceStatus}))}>{statuses.map(status=><option key={status}>{status}</option>)}</Select></td></tr>)}</tbody></table></div>:<Empty text="No assigned active students" description="This session has no eligible Students."/>}<div className="actions"><Button className="secondary" onClick={()=>setRosterSession(null)}>Cancel</Button><Button disabled={busy||!students.length} onClick={saveRoster}>Save attendance</Button></div></Card>}
    <Card><h2>Attendance sessions</h2>{sessions?.results.length?<><div className="table-wrap"><table><thead><tr><th>Date / title</th><th>Teacher / creator</th><th>Notes</th><th>Records</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{sessions.results.map(item=><tr key={item.id}><td><strong>{item.title||'Attendance session'}</strong><small className="table-secondary">{item.date}</small></td><td>{item.teacher_name||'Admin session'}<small className="table-secondary">Created by user #{item.created_by}</small></td><td>{item.notes||'—'}</td><td>{item.record_count}</td><td>{new Date(item.updated_at).toLocaleString()}</td><td><div className="row-actions"><Button className="secondary compact" onClick={()=>beginSession(item)}><Edit size={14}/> Edit</Button><Button className="ghost compact" onClick={()=>setRemove({kind:'session',id:item.id})}><Trash2 size={14}/> Delete</Button></div></td></tr>)}</tbody></table></div><Pagination page={Number(params.get('session_page')||1)} total={sessions.count} pageSize={20} hasPrevious={Boolean(sessions.previous)} hasNext={Boolean(sessions.next)} onPage={value=>setFilter('session_page',String(value))}/></>:!error&&<Empty icon={Clock3} text="No attendance sessions" description="Create a session to begin marking a roster."/>}</Card>
    <Card><h2>Attendance history</h2>{records?.results.length?<><div className="table-wrap"><table><thead><tr><th>Date</th><th>Student</th><th>Status</th><th>Session</th><th>Recorded by</th><th>Notes</th><th>Actions</th></tr></thead><tbody>{records.results.map(record=>{const canManage=Boolean(user?.is_admin||record.recorded_by===user?.id);return <tr key={record.id}><td>{record.date}<small className="table-secondary">Updated {new Date(record.updated_at).toLocaleDateString()}</small></td><td><strong>{record.student_name}</strong></td><td><Badge tone={record.status}>{record.status}</Badge></td><td>{sessionOptions.find(s=>s.id===record.session)?.title||'—'}</td><td>{record.recorded_by_name||`User #${record.recorded_by}`}</td><td>{record.notes||'—'}</td><td>{canManage&&<div className="row-actions"><Button className="secondary compact" onClick={()=>setRecordForm(record)}><Edit size={14}/> Edit</Button><Button className="ghost compact" onClick={()=>setRemove({kind:'record',id:record.id})}><Trash2 size={14}/> Delete</Button></div>}</td></tr>;})}</tbody></table></div><Pagination page={Number(params.get('page')||1)} total={records.count} pageSize={20} hasPrevious={Boolean(records.previous)} hasNext={Boolean(records.next)} onPage={value=>setFilter('page',String(value))}/></>:!error&&<Empty icon={CalendarCheck} text="No attendance history" description="Saved attendance records will appear here."/>}</Card>
    {recordForm&&<Card className="editor-card"><h2>Edit attendance record</h2><div className="form-grid"><Input label="Date" type="date" value={recordForm.date} onChange={e=>setRecordForm({...recordForm,date:e.target.value})}/><Select label="Status" value={recordForm.status} onChange={e=>setRecordForm({...recordForm,status:e.target.value as AttendanceStatus})}>{statuses.map(s=><option key={s}>{s}</option>)}</Select><Select label="Session" value={String(recordForm.session||'')} onChange={e=>setRecordForm({...recordForm,session:e.target.value?Number(e.target.value):null})}><option value="">No session</option>{sessionOptions.map(s=><option key={s.id} value={s.id}>{s.title||s.date}</option>)}</Select></div><Textarea label="Attendance notes" rows={3} value={recordForm.notes} onChange={e=>setRecordForm({...recordForm,notes:e.target.value})}/><div className="actions"><Button className="secondary" onClick={()=>setRecordForm(null)}>Cancel</Button><Button disabled={busy} onClick={saveRecord}>Save record</Button></div></Card>}
    <ConfirmDialog open={Boolean(remove)} title={`Delete ${remove?.kind==='session'?'session':'attendance record'}?`} message="This action is permanent and remains subject to backend ownership and protected-record rules." confirmLabel="Delete" danger busy={busy} onCancel={()=>setRemove(null)} onConfirm={confirmDelete}/>
  </>;
}
