import {useEffect,useMemo,useState} from 'react';
import {BookOpen,Edit,Plus,Trash2,X} from 'lucide-react';
import {useSearchParams} from 'react-router-dom';
import {api} from '../services/api';
import {apiErrorMessage} from '../utils/apiError';
import {getAllPages} from '../utils/pagination';
import type {HifzProgress,HifzStatus,Page,RevisionStatus,Student,Surah} from '../types';
import {Badge,Button,Card,Empty,Input,PageHeader,Select,Skeleton,Textarea} from '../components/UI';
import Pagination from '../components/Pagination';
import ConfirmDialog from '../components/ConfirmDialog';
import Feedback from '../components/Feedback';

type FormState={student:string;surah:string;juz:string;status:HifzStatus;progress_percentage:string;date_started:string;date_completed:string;revision_status:RevisionStatus;teacher_notes:string};
const blank:FormState={student:'',surah:'',juz:'',status:'not_started',progress_percentage:'0',date_started:'',date_completed:'',revision_status:'not_due',teacher_notes:''};
const statuses:HifzStatus[]=['not_started','in_progress','completed','revision'];
const revisions:RevisionStatus[]=['not_due','due','current','complete'];
const label=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());

export default function Hifz(){
  const [params,setParams]=useSearchParams(); const query=params.toString();
  const [page,setPage]=useState<Page<HifzProgress>|null>(null); const [students,setStudents]=useState<Student[]>([]); const [surahs,setSurahs]=useState<Surah[]>([]);
  const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [feedback,setFeedback]=useState('');
  const [editing,setEditing]=useState<HifzProgress|null|undefined>(undefined); const [form,setForm]=useState<FormState>(blank); const [busy,setBusy]=useState(false); const [remove,setRemove]=useState<HifzProgress|null>(null);
  const selectedStudent=useMemo(()=>students.find(s=>String(s.id)===params.get('student')),[students,params]);
  async function load(){try{const {data}=await api.get<Page<HifzProgress>>(`/hifz/?${query}`);setPage(data);setError('');}catch(reason){setError(apiErrorMessage(reason,'Unable to load Hifz progress.'));setPage(null);}finally{setLoading(false);}}
  useEffect(()=>{let active=true;api.get<Page<HifzProgress>>(`/hifz/?${query}`).then(({data})=>{if(active){setPage(data);setError('');}}).catch(reason=>{if(active){setError(apiErrorMessage(reason,'Unable to load Hifz progress.'));setPage(null);}}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[query]);
  useEffect(()=>{let active=true;Promise.all([getAllPages<Student>('/students/?status=active'),api.get<Surah[]>('/hifz/surahs/')]).then(([studentRows,surahResponse])=>{if(active){setStudents(studentRows);setSurahs(surahResponse.data);}}).catch(reason=>{if(active)setError(apiErrorMessage(reason,'Unable to load Hifz form options.'));});return()=>{active=false;};},[]);
  function setFilter(key:string,value:string){setLoading(true);const next=new URLSearchParams(params);if(value)next.set(key,value);else next.delete(key);if(key!=='page')next.delete('page');setParams(next);}
  function open(record?:HifzProgress){setEditing(record||null);setForm(record?{student:String(record.student),surah:String(record.surah),juz:String(record.juz),status:record.status,progress_percentage:String(record.progress_percentage),date_started:record.date_started||'',date_completed:record.date_completed||'',revision_status:record.revision_status,teacher_notes:record.teacher_notes}:blank);setError('');}
  async function save(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');const payload={student:Number(form.student),surah:Number(form.surah),juz:Number(form.juz),status:form.status,progress_percentage:Number(form.progress_percentage),date_started:form.date_started||null,date_completed:form.date_completed||null,revision_status:form.revision_status,teacher_notes:form.teacher_notes};try{if(editing)await api.patch(`/hifz/${editing.id}/`,payload);else await api.post('/hifz/',payload);setEditing(undefined);setFeedback(editing?'Hifz progress updated.':'Hifz progress created.');await load();}catch(reason){setError(apiErrorMessage(reason,'Unable to save Hifz progress.'));}finally{setBusy(false);}}
  async function confirmDelete(){if(!remove)return;setBusy(true);try{await api.delete(`/hifz/${remove.id}/`);setRemove(null);setFeedback('Hifz progress deleted.');await load();}catch(reason){setError(apiErrorMessage(reason,'Unable to delete Hifz progress.'));setRemove(null);}finally{setBusy(false);}}
  const currentPage=Number(params.get('page')||1);
  return <>
    <PageHeader eyebrow="Learning records" title="Hifz Progress" description="Track memorization, completion, revision, and teacher guidance." actions={<Button type="button" onClick={()=>open()}><Plus size={17}/> Add progress</Button>}/>
    {feedback&&<Feedback message={feedback} onDismiss={()=>setFeedback('')}/>}
    {error&&<Feedback tone="error" message={error} onDismiss={()=>setError('')}/>}
    {params.get('student')&&<div className="filter-notice"><span>Showing Hifz progress for <strong>{selectedStudent?.full_name||`student #${params.get('student')}`}</strong></span><Button className="secondary compact" onClick={()=>setFilter('student','')}><X size={15}/> Clear Student</Button></div>}
    <Card><div className="toolbar"><Select aria-label="Student filter" value={params.get('student')||''} onChange={e=>setFilter('student',e.target.value)}><option value="">All students</option>{students.map(s=><option key={s.id} value={s.id}>{s.full_name}</option>)}</Select><Select aria-label="Hifz status" value={params.get('status')||''} onChange={e=>setFilter('status',e.target.value)}><option value="">All statuses</option>{statuses.map(s=><option key={s} value={s}>{label(s)}</option>)}</Select><Select aria-label="Juz filter" value={params.get('juz')||''} onChange={e=>setFilter('juz',e.target.value)}><option value="">All Juz</option>{Array.from({length:30},(_,i)=>i+1).map(j=><option key={j}>{j}</option>)}</Select><Select aria-label="Revision status" value={params.get('revision_status')||''} onChange={e=>setFilter('revision_status',e.target.value)}><option value="">All revision states</option>{revisions.map(s=><option key={s} value={s}>{label(s)}</option>)}</Select><Select aria-label="Ordering" value={params.get('ordering')||'-updated_at'} onChange={e=>setFilter('ordering',e.target.value)}><option value="-updated_at">Recently updated</option><option value="updated_at">Oldest update</option><option value="-progress_percentage">Highest progress</option><option value="progress_percentage">Lowest progress</option><option value="surah">Surah order</option></Select></div>
      {loading?<Skeleton rows={6}/>:page?.results.length?<><div className="table-wrap"><table><thead><tr><th>Student / Surah</th><th>Juz</th><th>Progress</th><th>Status</th><th>Revision</th><th>Dates</th><th>Actions</th></tr></thead><tbody>{page.results.map(row=><tr key={row.id}><td><strong>{row.student_name}</strong><small className="table-secondary">{row.surah}. {row.surah_name}</small></td><td>{row.juz}</td><td><div className="progress-cell"><strong>{row.progress_percentage}% memorized</strong><span><i style={{width:`${row.progress_percentage}%`}}/></span></div></td><td><Badge tone={row.status}>{label(row.status)}</Badge></td><td><Badge tone={row.revision_status}>{label(row.revision_status)}</Badge></td><td>{row.date_started||'Not started'}<small className="table-secondary">Completed: {row.date_completed||'—'}</small></td><td><div className="row-actions"><Button className="secondary compact" onClick={()=>open(row)}><Edit size={14}/> Edit</Button><Button className="ghost compact" onClick={()=>setRemove(row)}><Trash2 size={14}/> Delete</Button></div></td></tr>)}</tbody></table></div><Pagination page={currentPage} total={page.count} pageSize={20} hasPrevious={Boolean(page.previous)} hasNext={Boolean(page.next)} onPage={value=>setFilter('page',String(value))}/></>:!error&&<Empty icon={BookOpen} text="No Hifz progress found" description="Create progress or change the current filters."/>}
    </Card>
    {editing!==undefined&&<Card className="editor-card"><h2>{editing?'Edit':'Add'} Hifz progress</h2><form onSubmit={save}><div className="form-grid"><Select label="Student" required value={form.student} onChange={e=>setForm({...form,student:e.target.value})}><option value="">Select a student</option>{students.map(s=><option key={s.id} value={s.id}>{s.full_name}</option>)}</Select><Select label="Surah" required value={form.surah} onChange={e=>setForm({...form,surah:e.target.value})}><option value="">Select a Surah</option>{surahs.map(s=><option key={s.number} value={s.number}>{s.number}. {s.name}</option>)}</Select><Select label="Juz" required value={form.juz} onChange={e=>setForm({...form,juz:e.target.value})}><option value="">Select Juz</option>{Array.from({length:30},(_,i)=>i+1).map(j=><option key={j}>{j}</option>)}</Select><Select label="Memorization status" value={form.status} onChange={e=>setForm({...form,status:e.target.value as HifzStatus})}>{statuses.map(s=><option key={s} value={s}>{label(s)}</option>)}</Select><Input label="Progress percentage" type="number" min="0" max="100" required value={form.progress_percentage} onChange={e=>setForm({...form,progress_percentage:e.target.value})}/><Select label="Revision status" value={form.revision_status} onChange={e=>setForm({...form,revision_status:e.target.value as RevisionStatus})}>{revisions.map(s=><option key={s} value={s}>{label(s)}</option>)}</Select><Input label="Date started" type="date" value={form.date_started} onChange={e=>setForm({...form,date_started:e.target.value})}/><Input label="Date completed" type="date" value={form.date_completed} onChange={e=>setForm({...form,date_completed:e.target.value})}/></div><Textarea label="Teacher notes" rows={4} value={form.teacher_notes} onChange={e=>setForm({...form,teacher_notes:e.target.value})}/><div className="actions"><Button type="button" className="secondary" onClick={()=>setEditing(undefined)}>Cancel</Button><Button disabled={busy}>{busy?'Saving…':'Save progress'}</Button></div></form></Card>}
    <ConfirmDialog open={Boolean(remove)} title="Delete Hifz progress?" message="This progress record will be permanently removed." confirmLabel="Delete progress" danger busy={busy} onCancel={()=>setRemove(null)} onConfirm={confirmDelete}/>
  </>;
}
