import {useEffect,useState} from 'react';
import {Link,useNavigate,useParams,useSearchParams} from 'react-router-dom';
import {Edit,Plus,Search,Trash2,UsersRound} from 'lucide-react';
import {api} from '../services/api';
import {apiErrorMessage} from '../utils/apiError';
import {Avatar,Badge,Button,Card,Empty,Input,PageHeader,Select,Skeleton,Textarea} from '../components/UI';
import ProtectedProfileImage from '../components/ProtectedProfileImage';
import ProfileImageManager from '../components/ProfileImageManager';
import ConfirmDialog from '../components/ConfirmDialog';
import Feedback from '../components/Feedback';
import Pagination from '../components/Pagination';
import {useAuth} from '../context/auth';
import type {Guardian,Page,Teacher} from '../types';

type Kind='teachers'|'guardians';
const displayName=(row:Teacher|Guardian)=>'name' in row?row.name:`${row.first_name} ${row.last_name}`.trim();

export function PeopleList({kind}:{kind:Kind}){
  const {user}=useAuth();const [params,setParams]=useSearchParams();const query=params.toString();const [data,setData]=useState<Page<Teacher|Guardian>|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [search,setSearch]=useState(params.get('search')||'');
  useEffect(()=>{let active=true;api.get<Page<Teacher|Guardian>>(`/${kind}/?${query}`).then(response=>{if(active){setData(response.data);setError('');}}).catch(reason=>{if(active){setData(null);setError(apiErrorMessage(reason,'Unable to load records.'));}}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[kind,query]);
  function setFilter(key:string,value:string){setLoading(true);const next=new URLSearchParams(params);if(value)next.set(key,value);else next.delete(key);if(key!=='page')next.delete('page');setParams(next);}
  const title=kind==='teachers'?'Teachers':'Parents / Guardians';const currentPage=Number(params.get('page')||1);
  return <><PageHeader eyebrow="People directory" title={title} description={`Search and review ${title.toLowerCase()} and their associated students.`} actions={user?.is_admin?<Link className="btn" to={`/${kind}/new`}><Plus size={17}/> Add {kind==='teachers'?'Teacher':'Guardian'}</Link>:undefined}/><Card><form className="toolbar" onSubmit={e=>{e.preventDefault();setFilter('search',search);}}><label className="search"><Search size={17}/><input aria-label={`Search ${kind}`} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name or contact"/></label><Select aria-label="Active status" value={params.get('is_active')||''} onChange={e=>setFilter('is_active',e.target.value)}><option value="">All statuses</option><option value="true">Active</option><option value="false">Inactive</option></Select><Button>Search</Button></form>{error?<Feedback tone="error" message={error}/>:loading?<Skeleton rows={6}/>:data?.results.length?<><div className="table-wrap"><table><thead><tr><th>Name</th><th>Contact</th><th>Students</th><th>Status</th><th>Actions</th></tr></thead><tbody>{data.results.map(row=>{const teacher=kind==='teachers'?row as Teacher:null;const name=displayName(row);return <tr key={row.id}><td><div className="actor-cell">{teacher?<ProtectedProfileImage endpoint={`/teachers/${teacher.id}/profile-image/`} hasImage={teacher.has_profile_image} name={name} size="sm"/>:<Avatar name={name} size="sm"/>}<span><Link to={`/${kind}/${row.id}`}><strong>{name}</strong></Link><small>{kind==='teachers'?'Teacher profile':'Guardian record'}</small></span></div></td><td><strong>{row.phone||'—'}</strong><small className="table-secondary">{row.email||'No email'}</small></td><td>{row.student_count}</td><td><Badge tone={row.is_active?'active':'inactive'}>{row.is_active?'Active':'Inactive'}</Badge></td><td><Link className="text-link" to={`/${kind}/${row.id}`}>View details</Link></td></tr>;})}</tbody></table></div><Pagination page={currentPage} total={data.count} pageSize={20} hasPrevious={Boolean(data.previous)} hasNext={Boolean(data.next)} onPage={value=>setFilter('page',String(value))}/></>:<Empty icon={UsersRound} text={`No ${title.toLowerCase()} found`} description="Change the filters or add a new record."/>}</Card></>;
}

export function PeopleProfile({kind}:{kind:Kind}){
  const {id}=useParams();const {user}=useAuth();const navigate=useNavigate();const [row,setRow]=useState<Teacher|Guardian|null>(null);const [error,setError]=useState('');const [feedback,setFeedback]=useState('');const [imageVersion,setImageVersion]=useState(0);const [remove,setRemove]=useState(false);const [busy,setBusy]=useState(false);
  useEffect(()=>{let active=true;api.get<Teacher|Guardian>(`/${kind}/${id}/`).then(response=>{if(active)setRow(response.data);}).catch(reason=>{if(active)setError(apiErrorMessage(reason,'Unable to load this record.'));});return()=>{active=false;};},[id,kind]);
  async function toggle(){if(!row)return;setBusy(true);try{const {data}=await api.patch<Teacher|Guardian>(`/${kind}/${id}/`,{is_active:!row.is_active});setRow(data);setFeedback(`${kind==='teachers'?'Teacher':'Guardian'} status updated.`);}catch(reason){setError(apiErrorMessage(reason,'Unable to update status.'));}finally{setBusy(false);}}
  async function confirmDelete(){setBusy(true);try{await api.delete(`/${kind}/${id}/`);navigate(`/${kind}`);}catch(reason){setRemove(false);setError(apiErrorMessage(reason,'This record could not be deleted. It may be protected by linked records.'));}finally{setBusy(false);}}
  if(!row)return error?<Feedback tone="error" message={error}/>:<Skeleton rows={4}/>;const teacher=kind==='teachers'?row as Teacher:null;const guardian=kind==='guardians'?row as Guardian:null;const name=displayName(row);
  return <><PageHeader eyebrow="People directory" title={kind==='teachers'?'Teacher Profile':'Guardian Profile'} description="Review contact information, status, and associated students." actions={user?.is_admin?<><Link className="btn secondary" to={`/${kind}/${id}/edit`}><Edit size={16}/> Edit</Link><Button className={row.is_active?'secondary':''} onClick={toggle} disabled={busy}>{row.is_active?'Deactivate':'Activate'}</Button><Button className="danger" onClick={()=>setRemove(true)}><Trash2 size={16}/> Delete</Button></>:undefined}/>{feedback&&<Feedback message={feedback} onDismiss={()=>setFeedback('')}/>} {error&&<Feedback tone="error" message={error} onDismiss={()=>setError('')}/>}<div className="profile-hero">{teacher?<ProtectedProfileImage endpoint={`/teachers/${teacher.id}/profile-image/`} hasImage={teacher.has_profile_image} name={name} size="lg" version={imageVersion}/>:<Avatar name={name} size="lg"/>}<div><h1>{name}</h1><p>{kind==='teachers'?'Teacher':'Parent / guardian'}</p></div><span className="profile-status"><Badge tone={row.is_active?'active':'inactive'}>{row.is_active?'Active':'Inactive'}</Badge></span></div><div className="profile-grid">
    <Card><h2>Contact information</h2><dl><dt>Email</dt><dd>{row.email||'—'}</dd><dt>Phone</dt><dd>{row.phone||'—'}</dd>{guardian&&<><dt>Address</dt><dd>{guardian.address||'—'}</dd><dt>Created</dt><dd>{new Date(guardian.created_at).toLocaleString()}</dd><dt>Last updated</dt><dd>{new Date(guardian.updated_at).toLocaleString()}</dd></>}</dl></Card>
    {teacher&&<Card><h2>Profile photo</h2><ProfileImageManager name={name} endpoint={`/teachers/${teacher.id}/profile-image/`} hasImage={teacher.has_profile_image} onChanged={hasImage=>{setRow(current=>current?{...current,has_profile_image:hasImage}:current);setImageVersion(value=>value+1);}}/></Card>}
    <Card className="wide"><h2>Associated students <span className="heading-count">{row.student_count}</span></h2>{row.students.length?<div className="table-wrap"><table><thead><tr><th>Student</th><th>Student ID</th></tr></thead><tbody>{row.students.map(student=><tr key={student.id}><td><Link to={`/students/${student.id}`}><strong>{student.name}</strong></Link></td><td>{student.student_id}</td></tr>)}</tbody></table></div>:<Empty text="No students assigned" description="Associated Student records will appear here."/>}</Card>
  </div><ConfirmDialog open={remove} title={`Delete this ${kind==='teachers'?'Teacher':'Guardian'}?`} message="Deletion may be blocked when protected Student or historical records exist." confirmLabel="Delete record" danger busy={busy} onCancel={()=>setRemove(false)} onConfirm={confirmDelete}/></>;
}

export function PeopleForm({kind}:{kind:Kind}){
  const {id}=useParams();const navigate=useNavigate();const editing=Boolean(id);const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(editing);const [error,setError]=useState('');const [form,setForm]=useState({username:'',password:'',first_name:'',last_name:'',name:'',email:'',phone:'',address:'',is_active:true});
  useEffect(()=>{if(!id)return;api.get<Teacher|Guardian>(`/${kind}/${id}/`).then(({data})=>setForm(current=>({...current,...data}))).catch(reason=>setError(apiErrorMessage(reason,'Unable to load this record.'))).finally(()=>setLoading(false));},[id,kind]);
  function change(key:string,value:string|boolean){setForm(current=>({...current,[key]:value}));}
  async function save(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');const payload=kind==='teachers'?{...(editing?{}:{username:form.username,password:form.password}),first_name:form.first_name,last_name:form.last_name,email:form.email,phone:form.phone,is_active:form.is_active}:{name:form.name,email:form.email,phone:form.phone,address:form.address,is_active:form.is_active};try{const {data}=editing?await api.patch<Teacher|Guardian>(`/${kind}/${id}/`,payload):await api.post<Teacher|Guardian>(`/${kind}/`,payload);navigate(`/${kind}/${data.id}`);}catch(reason){setError(apiErrorMessage(reason,'Unable to save this record.'));}finally{setBusy(false);}}
  if(loading)return <Skeleton rows={5}/>;return <><PageHeader eyebrow="People management" title={`${editing?'Edit':'Add'} ${kind==='teachers'?'Teacher':'Guardian'}`} description="Maintain contact details and active status using existing application permissions."/>{error&&<Feedback tone="error" message={error}/>}<Card className="form-card"><form onSubmit={save}><div className="form-grid">{kind==='teachers'?<>{!editing&&<><Input label="Username" required value={form.username} onChange={e=>change('username',e.target.value)}/><Input label="Initial password" type="password" required minLength={8} value={form.password} onChange={e=>change('password',e.target.value)}/></>}<Input label="First name" required value={form.first_name} onChange={e=>change('first_name',e.target.value)}/><Input label="Last name" required value={form.last_name} onChange={e=>change('last_name',e.target.value)}/></>:<Input label="Guardian name" required value={form.name} onChange={e=>change('name',e.target.value)}/>}<Input label="Email" type="email" value={form.email} onChange={e=>change('email',e.target.value)}/><Input label="Phone" required={kind==='guardians'} value={form.phone} onChange={e=>change('phone',e.target.value)}/><Select label="Status" value={String(form.is_active)} onChange={e=>change('is_active',e.target.value==='true')}><option value="true">Active</option><option value="false">Inactive</option></Select></div>{kind==='guardians'&&<Textarea label="Address" rows={4} value={form.address} onChange={e=>change('address',e.target.value)}/>}<div className="actions"><Button type="button" className="secondary" onClick={()=>navigate(-1)}>Cancel</Button><Button disabled={busy}>{busy?'Saving…':'Save record'}</Button></div></form></Card></>;
}
