import {useEffect,useState} from 'react';
import {useNavigate,useParams} from 'react-router-dom';
import {api} from '../services/api';
import {apiErrorMessage} from '../utils/apiError';
import {Button,Card,Input,PageHeader,Select,Textarea} from '../components/UI';
import {useAuth} from '../context/auth';
import type {Guardian,Student,Teacher} from '../types';
import ProfileImageEditor from '../components/ProfileImageEditor';
import {getAllPages} from '../utils/pagination';

const blank={student_id:'',first_name:'',last_name:'',gender:'male',date_of_birth:'',phone:'',email:'',address:'',guardian_name:'',guardian_phone:'',guardian_relationship:'',enrollment_date:new Date().toISOString().slice(0,10),status:'active',assigned_teacher:null,primary_guardian:null,notes:''};
export default function StudentForm(){
  const {id}=useParams();const navigate=useNavigate();const {user}=useAuth();
  const [form,setForm]=useState<Record<string,unknown>>(blank);const [teachers,setTeachers]=useState<Teacher[]>([]);const [guardians,setGuardians]=useState<Guardian[]>([]);const [error,setError]=useState('');const [hasProfileImage,setHasProfileImage]=useState(false);const [profileFile,setProfileFile]=useState<File|null>(null);const [removeProfileImage,setRemoveProfileImage]=useState(false);const [busy,setBusy]=useState(false);
  useEffect(()=>{let active=true;const requests:Promise<unknown>[]=[getAllPages<Guardian>('/guardians/?is_active=true').then(rows=>{if(active)setGuardians(rows);})];if(id)requests.push(api.get<Student>(`/students/${id}/`).then(response=>{if(active){setForm(response.data as unknown as Record<string,unknown>);setHasProfileImage(response.data.has_profile_image);}}));if(user?.is_admin)requests.push(getAllPages<Teacher>('/teachers/?is_active=true').then(rows=>{if(active)setTeachers(rows);}));Promise.all(requests).catch(reason=>{if(active)setError(apiErrorMessage(reason,'Unable to load student form options.'));});return()=>{active=false;};},[id,user?.is_admin]);
  function change(key:string,value:unknown){setForm(current=>({...current,[key]:value}));}
  async function save(event:React.FormEvent){event.preventDefault();setError('');setBusy(true);try{const response=id?await api.patch<Student>(`/students/${id}/`,form):await api.post<Student>('/students/',form);const studentId=response.data.id;if(profileFile){const upload=new FormData();upload.append('image',profileFile);await api.post(`/students/${studentId}/profile-image/`,upload);}else if(removeProfileImage&&hasProfileImage)await api.delete(`/students/${studentId}/profile-image/`);navigate(`/students/${studentId}`);}catch(reason){setError(apiErrorMessage(reason,'Unable to save student.'));}finally{setBusy(false);}}
  const studentName=`${String(form.first_name||'')} ${String(form.last_name||'')}`.trim()||'Student';
  return <><PageHeader eyebrow="Student records" title={`${id?'Edit':'Add'} Student`} description="Maintain identity, enrolment, teacher assignment, guardian relationships, and record notes."/><Card className="form-card"><form onSubmit={save}>{error&&<div className="alert" role="alert">{error}</div>}
    <section className="form-section"><div className="section-heading"><h2>Student information</h2><p>Core identity, contact, and enrolment details.</p></div><div className="form-grid"><Input label="Student ID" required value={String(form.student_id||'')} onChange={e=>change('student_id',e.target.value)}/><Select label="Gender" value={String(form.gender)} onChange={e=>change('gender',e.target.value)}><option value="male">Male</option><option value="female">Female</option></Select><Input label="First name" required value={String(form.first_name||'')} onChange={e=>change('first_name',e.target.value)}/><Input label="Last name" required value={String(form.last_name||'')} onChange={e=>change('last_name',e.target.value)}/><Input label="Date of birth" type="date" required value={String(form.date_of_birth||'')} onChange={e=>change('date_of_birth',e.target.value)}/><Input label="Enrollment date" type="date" required value={String(form.enrollment_date||'')} onChange={e=>change('enrollment_date',e.target.value)}/><Input label="Phone" value={String(form.phone||'')} onChange={e=>change('phone',e.target.value)}/><Input label="Email" type="email" value={String(form.email||'')} onChange={e=>change('email',e.target.value)}/><Input label="Address" value={String(form.address||'')} onChange={e=>change('address',e.target.value)}/><Select label="Status" value={String(form.status)} onChange={e=>change('status',e.target.value)}><option value="active">Active</option><option value="inactive">Inactive</option></Select></div><Textarea label="General student notes" rows={4} value={String(form.notes||'')} onChange={e=>change('notes',e.target.value)} hint="Authored teacher notes are managed separately on the Student profile."/></section>
    <section className="form-section"><div className="section-heading"><h2>Profile photo</h2><p>Add an optional private photo for quick identification.</p></div><ProfileImageEditor name={studentName} endpoint={id?`/students/${id}/profile-image/`:undefined} hasImage={hasProfileImage} file={profileFile} removeRequested={removeProfileImage} disabled={busy} onFile={file=>{setProfileFile(file);setRemoveProfileImage(false);}} onRemove={()=>{setProfileFile(null);setRemoveProfileImage(true);}} onError={setError}/></section>
    <section className="form-section"><div className="section-heading"><h2>Relationships</h2><p>Select existing active Teacher and parent/Guardian records.</p></div><div className="form-grid">{user?.is_admin&&<Select label="Dedicated teacher" value={String(form.assigned_teacher??'')} onChange={e=>change('assigned_teacher',e.target.value?Number(e.target.value):null)}><option value="">Unassigned</option>{teachers.map(t=><option key={t.id} value={t.id}>{t.first_name} {t.last_name}</option>)}</Select>}<Select label="Primary parent / guardian" required value={String(form.primary_guardian??'')} onChange={e=>change('primary_guardian',e.target.value?Number(e.target.value):null)}><option value="">Select a Guardian</option>{guardians.map(g=><option key={g.id} value={g.id}>{g.name} — {g.phone}</option>)}</Select><Input label="Guardian relationship" required value={String(form.guardian_relationship||'')} onChange={e=>change('guardian_relationship',e.target.value)}/></div></section>
    <div className="actions"><Button type="button" className="secondary" disabled={busy} onClick={()=>navigate(-1)}>Cancel</Button><Button disabled={busy}>{busy?'Saving…':'Save student'}</Button></div>
  </form></Card></>;
}
