import {useEffect,useState} from 'react';
import {useNavigate,useParams} from 'react-router-dom';
import {api} from '../services/api';
import {apiErrorMessage} from '../utils/apiError';
import {Button,Card,Input,PageHeader,Select,Textarea} from '../components/UI';
import {useAuth} from '../context/auth';
import type {Guardian,Student,StudentWritePayload,Teacher} from '../types';
import ProfileImageEditor from '../components/ProfileImageEditor';
import {getAllPages} from '../utils/pagination';

type StudentFormState=Omit<StudentWritePayload,'assigned_teacher'>&{assigned_teacher:number|null};
const blank:StudentFormState={student_id:'',first_name:'',last_name:'',gender:'male',date_of_birth:'',phone:'',email:'',address:'',guardian_relationship:'',enrollment_date:new Date().toISOString().slice(0,10),status:'active',assigned_teacher:null,primary_guardian:null,notes:''};
function formFromStudent(student:Student):StudentFormState{return {student_id:student.student_id,first_name:student.first_name,last_name:student.last_name,gender:student.gender,date_of_birth:student.date_of_birth,phone:student.phone,email:student.email,address:student.address,guardian_relationship:student.guardian_relationship,enrollment_date:student.enrollment_date,status:student.status,assigned_teacher:student.assigned_teacher,primary_guardian:student.primary_guardian,notes:student.notes};}
function studentPayload(form:StudentFormState,isAdmin:boolean):StudentWritePayload{return {student_id:form.student_id,first_name:form.first_name,last_name:form.last_name,gender:form.gender,date_of_birth:form.date_of_birth,phone:form.phone,email:form.email,address:form.address,guardian_relationship:form.primary_guardian?form.guardian_relationship:'',enrollment_date:form.enrollment_date,status:form.status,...(isAdmin?{assigned_teacher:form.assigned_teacher}:{}),primary_guardian:form.primary_guardian,notes:form.notes};}
function genderValue(value:string):Student['gender']{return value==='female'?'female':'male';}
function statusValue(value:string):Student['status']{return value==='inactive'?'inactive':'active';}
export default function StudentForm(){
  const {id}=useParams();const navigate=useNavigate();const {user}=useAuth();
  const [form,setForm]=useState<StudentFormState>(blank);const [teachers,setTeachers]=useState<Teacher[]>([]);const [guardians,setGuardians]=useState<Guardian[]>([]);const [error,setError]=useState('');const [hasProfileImage,setHasProfileImage]=useState(false);const [profileFile,setProfileFile]=useState<File|null>(null);const [removeProfileImage,setRemoveProfileImage]=useState(false);const [busy,setBusy]=useState(false);
  useEffect(()=>{let active=true;const requests:Promise<unknown>[]=[getAllPages<Guardian>('/guardians/?is_active=true').then(rows=>{if(active)setGuardians(rows);})];if(id)requests.push(api.get<Student>(`/students/${id}/`).then(response=>{if(active){setForm(formFromStudent(response.data));setHasProfileImage(response.data.has_profile_image);}}));if(user?.is_admin)requests.push(getAllPages<Teacher>('/teachers/?is_active=true').then(rows=>{if(active)setTeachers(rows);}));Promise.all(requests).catch(reason=>{if(active)setError(apiErrorMessage(reason,'Unable to load student form options.'));});return()=>{active=false;};},[id,user?.is_admin]);
  function change<K extends keyof StudentFormState>(key:K,value:StudentFormState[K]){setForm(current=>({...current,[key]:value}));}
  async function save(event:React.FormEvent){event.preventDefault();if(busy)return;setError('');setBusy(true);let student:Student;try{const payload=studentPayload(form,Boolean(user?.is_admin));const response=id?await api.patch<Student>(`/students/${id}/`,payload):await api.post<Student>('/students/',payload);student=response.data;}catch(reason){setError(apiErrorMessage(reason,'Unable to save student.'));setBusy(false);return;}try{if(profileFile){const upload=new FormData();upload.append('image',profileFile);await api.post(`/students/${student.id}/profile-image/`,upload);}else if(removeProfileImage&&hasProfileImage)await api.delete(`/students/${student.id}/profile-image/`);navigate(`/students/${student.id}`,{state:{message:'Student saved successfully.',tone:'success'}});}catch{navigate(`/students/${student.id}`,{state:{message:profileFile?'Student was saved successfully, but the profile image could not be uploaded.':'Student was saved successfully, but the profile image could not be removed.',tone:'error'}});}finally{setBusy(false);}}
  const studentName=`${String(form.first_name||'')} ${String(form.last_name||'')}`.trim()||'Student';
  return <><PageHeader eyebrow="Student records" title={`${id?'Edit':'Add'} Student`} description="Maintain identity, enrolment, teacher assignment, guardian relationships, and record notes."/><Card className="form-card"><form onSubmit={save}>{error&&<div className="alert" role="alert">{error}</div>}
    <section className="form-section"><div className="section-heading"><h2>Student information</h2><p>Core identity, contact, and enrolment details.</p></div><div className="form-grid"><Input label="Student ID" required value={String(form.student_id||'')} onChange={e=>change('student_id',e.target.value)}/><Select label="Gender" value={String(form.gender)} onChange={e=>change('gender',genderValue(e.target.value))}><option value="male">Male</option><option value="female">Female</option></Select><Input label="First name" required value={String(form.first_name||'')} onChange={e=>change('first_name',e.target.value)}/><Input label="Last name" required value={String(form.last_name||'')} onChange={e=>change('last_name',e.target.value)}/><Input label="Date of birth" type="date" required value={String(form.date_of_birth||'')} onChange={e=>change('date_of_birth',e.target.value)}/><Input label="Enrollment date" type="date" required value={String(form.enrollment_date||'')} onChange={e=>change('enrollment_date',e.target.value)}/><Input label="Phone" value={String(form.phone||'')} onChange={e=>change('phone',e.target.value)}/><Input label="Email" type="email" value={String(form.email||'')} onChange={e=>change('email',e.target.value)}/><Input label="Address" value={String(form.address||'')} onChange={e=>change('address',e.target.value)}/><Select label="Status" value={String(form.status)} onChange={e=>change('status',statusValue(e.target.value))}><option value="active">Active</option><option value="inactive">Inactive</option></Select></div><Textarea label="General student notes" rows={4} value={String(form.notes||'')} onChange={e=>change('notes',e.target.value)} hint="Authored teacher notes are managed separately on the Student profile."/></section>
    <section className="form-section"><div className="section-heading"><h2>Profile photo</h2><p>Add an optional private photo for quick identification.</p></div><ProfileImageEditor name={studentName} endpoint={id?`/students/${id}/profile-image/`:undefined} hasImage={hasProfileImage} file={profileFile} removeRequested={removeProfileImage} disabled={busy} onFile={file=>{setProfileFile(file);setRemoveProfileImage(false);}} onRemove={()=>{setProfileFile(null);setRemoveProfileImage(true);}} onError={setError}/></section>
    <section className="form-section"><div className="section-heading"><h2>Relationships</h2><p>Teacher and parent/Guardian relationships are optional. Teacher-created Students are assigned to their Teacher automatically.</p></div><div className="form-grid">{user?.is_admin&&<Select label="Dedicated teacher" value={String(form.assigned_teacher??'')} onChange={e=>change('assigned_teacher',e.target.value?Number(e.target.value):null)}><option value="">No teacher assigned</option>{teachers.map(t=><option key={t.id} value={t.id}>{t.first_name} {t.last_name}</option>)}</Select>}<Select label="Primary parent / guardian" value={String(form.primary_guardian??'')} onChange={e=>change('primary_guardian',e.target.value?Number(e.target.value):null)}><option value="">No guardian assigned</option>{guardians.map(g=><option key={g.id} value={g.id}>{g.name} — {g.phone}</option>)}</Select><Input label="Guardian relationship" value={String(form.guardian_relationship||'')} disabled={!form.primary_guardian} onChange={e=>change('guardian_relationship',e.target.value)} hint={form.primary_guardian?'Optional relationship description.':'Select a Guardian to add a relationship description.'}/></div></section>
    <div className="actions"><Button type="button" className="secondary" disabled={busy} onClick={()=>navigate(-1)}>Cancel</Button><Button disabled={busy}>{busy?'Saving…':'Save student'}</Button></div>
  </form></Card></>;
}
