import {useEffect,useState} from 'react';
import {Link,useLocation,useNavigate,useParams} from 'react-router-dom';
import {BookOpen,CalendarCheck,Edit,Trash2} from 'lucide-react';
import {api} from '../services/api';
import {apiErrorMessage} from '../utils/apiError';
import type {AttendanceRecord,HifzProgress,Page,Student} from '../types';
import {Badge,Card,Empty,PageHeader,Skeleton} from '../components/UI';
import ProtectedProfileImage from '../components/ProtectedProfileImage';
import StudentNotes from '../components/StudentNotes';
import Feedback from '../components/Feedback';
import ConfirmDialog from '../components/ConfirmDialog';
import {Button} from '../components/UI';
import {useAuth} from '../context/auth';
import {formatDateTime} from '../utils/date';

export default function StudentProfile(){
  const {id}=useParams();const {user}=useAuth();const navigate=useNavigate();const location=useLocation();const navigationState=location.state as {message?:string;tone?:'success'|'error'}|null;const [feedback,setFeedback]=useState(navigationState?.message||'');const [feedbackTone]=useState<'success'|'error'>(navigationState?.tone||'success');const [student,setStudent]=useState<Student|null>(null);const [attendance,setAttendance]=useState<Page<AttendanceRecord>|null>(null);const [hifz,setHifz]=useState<Page<HifzProgress>|null>(null);const [error,setError]=useState('');const [attendanceError,setAttendanceError]=useState('');const [hifzError,setHifzError]=useState('');const [remove,setRemove]=useState(false);const [busy,setBusy]=useState(false);const [reload,setReload]=useState(0);
  useEffect(()=>{let active=true;api.get<Student>(`/students/${id}/`).then(response=>{if(active){setStudent(response.data);setError('');}}).catch(reason=>{if(active){setStudent(null);setError(apiErrorMessage(reason,'Unable to load this student.'));}});return()=>{active=false;};},[id,reload]);
  useEffect(()=>{let active=true;api.get<Page<AttendanceRecord>>(`/attendance/?student=${id}&ordering=-date`).then(response=>{if(active){setAttendance(response.data);setAttendanceError('');}}).catch(reason=>{if(active){setAttendance(null);setAttendanceError(apiErrorMessage(reason,'Unable to load attendance preview.'));}});api.get<Page<HifzProgress>>(`/hifz/?student=${id}&ordering=-updated_at`).then(response=>{if(active){setHifz(response.data);setHifzError('');}}).catch(reason=>{if(active){setHifz(null);setHifzError(apiErrorMessage(reason,'Unable to load Hifz preview.'));}});return()=>{active=false;};},[id,reload]);
  async function confirmDelete(){setBusy(true);try{await api.delete(`/students/${id}/`);navigate('/students',{replace:true});}catch(reason){setRemove(false);setError(apiErrorMessage(reason,'This Student could not be deleted. Linked protected records may need to be retained.'));}finally{setBusy(false);}}
  if(!student)return error?<div className="error-actions"><Feedback tone="error" message={error}/><Button type="button" className="secondary" onClick={()=>setReload(value=>value+1)}>Retry</Button></div>:<Skeleton rows={5}/>;
  return <><PageHeader eyebrow="Student records" title="Student Profile" description="Review identity, relationships, attendance, learning progress, and notes." actions={<><Link className="btn" to={`/students/${id}/edit`}><Edit size={17}/> Edit student</Link>{user?.is_admin&&<Button className="danger" type="button" onClick={()=>setRemove(true)}><Trash2 size={17}/> Delete Student</Button>}</>}/><div className="profile-hero"><ProtectedProfileImage endpoint={`/students/${student.id}/profile-image/`} hasImage={student.has_profile_image} name={student.full_name} size="lg"/><div><h1>{student.full_name}</h1><p>{student.student_id} · {student.gender}</p></div><span className="profile-status"><Badge tone={student.status}>{student.status}</Badge></span></div><div className="profile-grid">
    {feedback&&<div className="wide"><Feedback message={feedback} tone={feedbackTone} onDismiss={()=>setFeedback('')}/></div>}
    <Card><h2>Identity</h2><dl><dt>Student ID</dt><dd>{student.student_id}</dd><dt>Date of birth</dt><dd>{student.date_of_birth}</dd><dt>Gender</dt><dd>{student.gender}</dd><dt>Status</dt><dd><Badge tone={student.status}>{student.status}</Badge></dd></dl></Card>
    <Card><h2>Contact</h2><dl><dt>Phone</dt><dd>{student.phone||'—'}</dd><dt>Email</dt><dd>{student.email||'—'}</dd><dt>Address</dt><dd>{student.address||'—'}</dd></dl></Card>
    <Card><h2>Enrollment</h2><dl><dt>Enrollment date</dt><dd>{student.enrollment_date}</dd><dt>Assigned Teacher</dt><dd>{student.teacher?.name||'Unassigned'}</dd><dt>Teacher phone</dt><dd>{student.teacher?.phone||'—'}</dd><dt>Teacher email</dt><dd>{student.teacher?.email||'—'}</dd></dl></Card>
    <Card><h2>Primary Guardian</h2><dl><dt>Name</dt><dd>{student.parent?.name||'Not assigned'}</dd><dt>Relationship</dt><dd>{student.guardian_relationship||'—'}</dd><dt>Phone</dt><dd>{student.parent?.phone||'—'}</dd><dt>Email</dt><dd>{student.parent?.email||'—'}</dd></dl></Card>
    <Card><h2>Attendance</h2>{attendanceError?<Feedback tone="error" message={attendanceError}/>:<><p className="section-summary"><strong>{attendance?.count||0}</strong> attendance records</p>{attendance?.results.slice(0,3).map(record=><div className="activity" key={record.id}><div><strong>{record.date}</strong><small>{record.recorded_by_name||'Recorded attendance'}</small></div><Badge tone={record.status}>{record.status}</Badge></div>)}</>}<div className="quick-links"><Link to={`/attendance?student=${id}`}><CalendarCheck size={18}/> View full attendance</Link></div></Card>
    <Card><h2>Hifz</h2>{hifzError?<Feedback tone="error" message={hifzError}/>:<><p className="section-summary"><strong>{hifz?.count||0}</strong> progress records</p>{hifz?.results.slice(0,3).map(record=><div className="activity" key={record.id}><div><strong>{record.surah_name}</strong><small>Juz {record.juz} · {record.status.replaceAll('_',' ')}</small></div><b>{record.progress_percentage}%</b></div>)}</>}<div className="quick-links"><Link to={`/hifz?student=${id}`}><BookOpen size={18}/> View Hifz progress</Link></div></Card>
    <Card className="wide"><h2>General student notes</h2>{student.notes?<p className="long-copy">{student.notes}</p>:<Empty text="No general notes" description="General record notes can be added from Edit Student."/>}</Card>
    <Card className="wide"><h2>Authored teacher notes</h2><StudentNotes studentId={student.id}/></Card>
    <Card className="wide system-info"><h2>System information</h2><dl><dt>Created</dt><dd>{formatDateTime(student.created_at)}</dd><dt>Last updated</dt><dd>{formatDateTime(student.updated_at)}</dd></dl></Card>
  </div><ConfirmDialog open={remove} title="Delete this Student?" message="This permanently deletes the Student. Deletion may be blocked when protected attendance, Hifz, note, or other historical records exist." confirmLabel="Delete Student" danger busy={busy} onCancel={()=>setRemove(false)} onConfirm={confirmDelete}/></>;
}
