import {lazy,Suspense} from 'react';
import {Navigate,Route,Routes,useLocation} from 'react-router-dom';
import {useAuth} from './context/auth';
import AppLayout from './layouts/AppLayout';
import Login from './pages/Login';import StudentForm from './pages/StudentForm';import StudentProfile from './pages/StudentProfile';
import AdminRoute from './components/AdminRoute';import SuperuserRoute from './components/SuperuserRoute';import TeacherRoute from './components/TeacherRoute';import {Spinner} from './components/UI';

const Dashboard=lazy(()=>import('./pages/Dashboard'));const Students=lazy(()=>import('./pages/Students'));const TeacherProfile=lazy(()=>import('./pages/TeacherProfile'));const Attendance=lazy(()=>import('./pages/Attendance'));const Hifz=lazy(()=>import('./pages/Hifz'));const AuditLogs=lazy(()=>import('./pages/superuser/AuditLogs'));const SuperuserDashboard=lazy(()=>import('./pages/superuser/SuperuserDashboard'));const Users=lazy(()=>import('./pages/superuser/Users'));const UserDetails=lazy(()=>import('./pages/superuser/UserDetails'));const UserForm=lazy(()=>import('./pages/superuser/UserForm'));
const PeopleList=lazy(()=>import('./pages/People').then(module=>({default:module.PeopleList})));const PeopleProfile=lazy(()=>import('./pages/People').then(module=>({default:module.PeopleProfile})));const PeopleForm=lazy(()=>import('./pages/People').then(module=>({default:module.PeopleForm})));

function Protected(){const {user,loading}=useAuth(),location=useLocation();if(loading)return <Spinner/>;return user?<AppLayout/>:<Navigate to="/login" state={{from:location.pathname}} replace/>;}
export default function App(){return <Suspense fallback={<div className="route-loading" role="status" aria-live="polite"><Spinner/> Loading page…</div>}><Routes><Route path="/login" element={<Login/>}/><Route element={<Protected/>}><Route path="/dashboard" element={<Dashboard/>}/><Route element={<TeacherRoute/>}><Route path="/profile" element={<TeacherProfile/>}/></Route><Route path="/students" element={<Students/>}/><Route path="/students/new" element={<StudentForm/>}/><Route path="/students/:id" element={<StudentProfile/>}/><Route path="/students/:id/edit" element={<StudentForm/>}/><Route path="/hifz" element={<Hifz/>}/><Route path="/attendance" element={<Attendance/>}/><Route path="/guardians" element={<PeopleList kind="guardians"/>}/><Route path="/guardians/:id" element={<PeopleProfile kind="guardians"/>}/><Route element={<AdminRoute/>}><Route path="/teachers" element={<PeopleList kind="teachers"/>}/><Route path="/teachers/new" element={<PeopleForm kind="teachers"/>}/><Route path="/teachers/:id" element={<PeopleProfile kind="teachers"/>}/><Route path="/teachers/:id/edit" element={<PeopleForm kind="teachers"/>}/><Route path="/guardians/new" element={<PeopleForm kind="guardians"/>}/><Route path="/guardians/:id/edit" element={<PeopleForm kind="guardians"/>}/><Route path="/audit" element={<AuditLogs/>}/></Route><Route element={<SuperuserRoute/>}><Route path="/superuser" element={<SuperuserDashboard/>}/><Route path="/superuser/users" element={<Users/>}/><Route path="/superuser/users/new" element={<UserForm/>}/><Route path="/superuser/users/:id" element={<UserDetails/>}/><Route path="/superuser/users/:id/edit" element={<UserForm/>}/><Route path="/superuser/audit" element={<Navigate to="/audit" replace/>}/></Route></Route><Route path="*" element={<Navigate to="/dashboard"/>}/></Routes></Suspense>;}
